# Generated by Django 4.1.4 on 2022-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('breed', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
